CREATE DATABASE foodreviewdb;

USE foodreviewdb;

CREATE TABLE foods (
	id VARCHAR(64),
	name VARCHAR(30),
	description TEXT,
	date_added DATETIME,
	PRIMARY KEY (id)
);

CREATE USER 'foodusr' IDENTIFIED BY 'foodpwd';

GRANT ALL ON *.* TO 'foodusr'@'localhost' IDENTIFIED BY 'foodpwd';

GRANT ALL ON *.* TO 'foodusr' IDENTIFIED BY 'foodpwd';

INSERT INTO foods VALUES ('93796604-e98c-48f0-bd4c-ec33130ef9c8', 'Cheeseburger', 'A cheeseburger is a hamburger topped with cheese. Traditionally, the slice of cheese is placed on top of the meat patty, but the burger can include variations in structure, ingredients and composition. The cheese is usually added to the cooking hamburger patty shortly before serving, which allows the cheese to melt. As with other hamburgers, a cheeseburger may include toppings, such as lettuce, tomato, onion, pickles, bacon, mayonnaise, ketchup, mustard or other toppings.', '2020-04-14 17:34:07');
INSERT INTO foods VALUES ('a335c1fe-e6ee-402a-bc2d-4ce7f0691675', 'Cheesecake', 'Cheesecake is a sweet dessert consisting of one or more layers. The main, and thickest layer, consists of a mixture of soft, fresh cheese (typically cream cheese or ricotta), eggs, and sugar. If there is a bottom layer, it often consists of a crust or base made from crushed cookies (or digestive biscuits), graham crackers, pastry, or sometimes sponge cake. It may be baked or unbaked (usually refrigerated). Cheesecake is usually sweetened with sugar and may be flavored in many different ways. It may be flavored by adding vanilla, spices, lemon, chocolate, pumpkin, or other flavors to the cheese layer. Additional flavors and visual appeal may be added by topping the finished pie with fruit, whipped cream, nuts, cookies, fruit sauce, chocolate syrup, or other toppings.', '2020-04-14 17:34:07');
INSERT INTO foods VALUES ('4975456c-a872-4cec-b111-4e30aa3a00c4', 'Siew yoke', 'Siew yoke is a variety of siu mei, or roasted meat dishes, in Cantonese cuisine. It is made by roasting an entire pig with seasonings, such as salt and vinegar in a charcoal furnace at high temperature. Roasted pigs of high quality have crisp skin and juicy and tender meat. Usually the meat is served plain with its skin, but it is sometimes served with soy sauce or hoisin sauce.', '2020-04-14 17:34:07');
INSERT INTO foods VALUES ('476f2a56-dcf9-4db8-8240-b6cee9282f90', 'Roast chicken', 'Roast chicken is chicken prepared as food by roasting whether in a home kitchen, over a fire, or with a rotisserie (rotary spit). Generally, the chicken is roasted with its own fat and juices by circulating the meat during roasting, and therefore, are usually cooked exposed to fire or heat with some type of rotary grill so that the circulation of these fats and juices is as efficient as possible. Roast chicken is a dish that appears in a wide variety of cuisines worldwide.', '2020-04-14 17:34:07');
INSERT INTO foods VALUES ('74861647-46d9-48e7-8475-7b6767be8eff', 'Ketoprak', 'Ketoprak is a vegetarian dish from Jakarta, Indonesia, consists of tofu, vegetables and rice cake, rice vermicelli served in peanut sauce.', '2020-04-14 17:34:07');
INSERT INTO foods VALUES ('c1e6203d-8f40-4f70-a5d4-6393bd5c5df8', 'Tortilla de patatas', 'Spanish omelette or Spanish tortilla is a traditional dish from Spain and one of the signature dishes in the Spanish cuisine. It is an omelette made with eggs and potatoes, optionally including onion. It is often served at room temperature as a tapa. It is commonly known in Spanish-speaking countries as tortilla de patatas, tortilla de papas or tortilla española.', '2020-04-14 17:34:07');
INSERT INTO foods VALUES ('5867e37c-6648-434f-b898-478eec031517', 'Filet mignon', 'Filet mignon is a steak cut of beef taken from the smaller end of the tenderloin, or psoas major of the cow carcass, usually a steer or heifer. In French, this cut is always called filet de bœuf ("beef fillet"), as filet mignon refers to pork tenderloin. The tenderloin runs along both sides of the spine, and is usually harvested as two long snake-shaped cuts of beef. The tenderloin is sometimes sold whole. When sliced along the short dimension, creating roughly round cuts, and tube cuts, the cuts (fillets) from the small forward end are considered to be filet mignon. Those from the center are tournedos; however, some butchers in the United States label all types of tenderloin steaks "filet mignon". In fact, the shape of the true filet mignon may be a hindrance when cooking, so most restaurants sell steaks from the wider end of the tenderloin – it is both cheaper and much more presentable.', '2020-04-14 17:34:07');
INSERT INTO foods VALUES ('f360a4af-b536-4cd2-a6fe-8fb59a2a39f3', 'Pempek', 'Pempek, mpek-mpek or empek-empek is a savoury Indonesian fishcake delicacy, made of fish and tapioca, from Palembang, South Sumatera, Indonesia. Pempek is served with rich sweet and sour sauce called kuah cuka or kuah cuko (lit. vinegar sauce), or just "cuko". Sometimes local people also eat the dish with yellow noodles and diced up cucumber to balance out the vinegar\'s sourness.', '2020-04-14 17:34:07');
INSERT INTO foods VALUES ('716627c3-d4a7-4871-b6d6-0c3800f9dee8', 'Shish taouk', 'Shish taoukis a traditional marinated chicken shish kebab of Middle Eastern cuisine. It is widely eaten in Armenia, Turkey, Azerbaijan, Lebanon, Egypt, Jordan, Syria, Palestine, Iraq, and Israel. A similar dish in Persian cuisine is the traditional jujeh kabab. It is also served in kebab houses in many cities around the world.', '2020-04-14 17:34:07');
INSERT INTO foods VALUES ('ef7228bc-1a59-4f16-abd8-3bd22e7bcc13', 'Takoyaki', 'Takoyaki is a ball-shaped Japanese snack or appetizer made of a wheat flour-based batter and cooked in a special molded pan. It is typically filled with minced or diced octopus (tako), tempura scraps (tenkasu), pickled ginger (beni shoga), and green onion (negi). The balls are brushed with takoyaki sauce (similar to Worcestershire sauce) and mayonnaise, and then sprinkled with green laver (aonori) and shavings of dried bonito (katsuobushi).', '2020-04-14 17:34:07');
INSERT INTO foods VALUES ('ce5fccca-1cdd-465c-a1ed-976ebf980f41', 'Tamagoyaki', 'Tamagoyaki  is a type of Japanese omelette, which is made by rolling together several layers of cooked egg. These are often prepared in a rectangular omelette pan called a makiyakinabe or tamagoyakiki.', '2020-04-14 17:34:07');
INSERT INTO foods VALUES ('61062125-1d7e-4bfc-a5b7-281192aa228b', 'Okonomiyaki', 'Okonomiyaki is a Japanese savory pancake containing a variety of ingredients in a wheat-flour-based batter; it is an example of Konamon (flour-based Japanese cuisine). The name is derived from the word okonomi, meaning "how you like" or "what you like", and yaki meaning "cooked" (usually fried). Okonomiyaki is mainly associated with the Kansai or Hiroshima areas of Japan, but is widely available throughout the country. Toppings and batters tend to vary according to region. In Tokyo, there is a semi-liquid okonomiyaki called monjayaki.', '2020-04-14 17:34:07');
INSERT INTO foods VALUES ('76c2d1d8-f2f1-48e9-88a4-7fafdd13e0cb', 'Onigiri', 'Onigiri also known as o-musubi, nigirimeshi, rice ball, is a Japanese food made from white rice formed into triangular or cylindrical shapes and often wrapped in nori (seaweed). Traditionally, an onigiri is filled with pickled ume (umeboshi), salted salmon, katsuobushi, kombu, tarako, or any other salty or sour ingredient as a natural preservative. Most Japanese convenience stores stock their onigiri with various fillings and flavors. There are even specialized shops which only sell onigiri to take out. Due to the popularity of this trend in Japan, onigiri has become a popular staple in Japanese restaurants worldwide.', '2020-04-14 17:34:07');
INSERT INTO foods VALUES ('3446441a-9544-4f8c-b2ca-ec1ecf183bd0', 'Tonkatsu', 'Tonkatsu is a Japanese dish that consists of a breaded, deep-fried/tempura pork cutlet. It involves cutting the pig\'s back center into 2-3 centimeter thick slices, coating with panko (bread crumbs), frying them in oil, and then serving with Japanese Worcestershire sauce, rice, and vegetable salad (mainly cabbage). The two main types are fillet and loin. Tonkatsu is often served with shredded cabbage, or on a bed of rice (making it a donburi dish, called Katsudon).', '2020-04-14 17:34:07');
INSERT INTO foods VALUES ('10be29ef-52bd-407e-9e5e-0f50935c424f', 'Gado-gado', 'Gado-gado is an Indonesian salad of slightly boiled, blanched or steamed vegetables and hard-boiled eggs, boiled potato, fried tofu and tempeh, and lontong (rice wrapped in a banana leaf), served with a peanut sauce dressing. In 2018, gado-gado is promoted as one of five national dishes of Indonesia.', '2020-04-14 17:34:07');
INSERT INTO foods VALUES ('e69a3d89-c7c5-4dfc-866d-304ab131c296', 'Shawarma', 'Shawarma is a dish in Middle Eastern cuisine consisting of meat cut into thin slices, stacked in a cone-like shape, and roasted on a slowly-turning vertical rotisserie or spit. Originally made of lamb or mutton, today\'s shawarma may also be chicken, turkey, beef, or veal. Thin slices are shaved off the cooked surface as it continuously rotates. Shawarma is one of the world\'s most popular street foods, especially in Egypt and the countries of the Levant, the Arabian Peninsula, and beyond.', '2020-04-14 17:34:07');
INSERT INTO foods VALUES ('e37d9a89-685e-4a0d-bf62-c4fed0777416', 'Chawanmushi', 'Chawanmushi is an egg custard dish found in Japan. Unlike many other custards, it is usually eaten as a dish in a meal, as chawanmushi contains savory rather than sweet ingredients. The custard consists of an egg mixture flavored with soy sauce, dashi, and mirin, with numerous ingredients such as shiitake mushrooms, kamaboko, yuri-ne (lily root), ginkgo and boiled shrimp placed into a tea-cup-like container. The recipe for the dish is similar to that of Chinese steamed eggs, but the toppings may often differ. Since egg custard can\'t be picked up by chopsticks, it\'s one of the few Japanese dishes that is eaten with a spoon.', '2020-04-14 17:34:07');